"""empty message

Revision ID: 11db968dcebb
Revises: c4bed6b5e64e
Create Date: 2023-04-03 23:23:28.313983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11db968dcebb'
down_revision = 'c4bed6b5e64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('users_from_id', sa.Integer(), nullable=False),
    sa.Column('users_to_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_from_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['users_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
